  - name: Install Postgresql
    apt:
      name: ['postgresql', 'python3-psycopg2']
      install_recommends: yes
    tags: PostgresqlInstall

  - name: Create Postgresql Database
    become: true # O ansible se torna root para execução dessa task
    become_user: postgres 
    postgresql_db:
      name: "{{ item.name }}"
      encoding: UTF-8
    with_items:
      - "{{ postgresql_databases }}"
    tags: PostgresqlDatabase
    
  - name: Create Postgresql User
    become: true # O ansible se torna root para execução dessa task
    become_user: postgres
    postgresql_user:
      name: "{{ item.name }}"
      password: "{{ item.password }}"
      priv: "{{ item.priv }}"
      db: "{{ item.base }}"
    with_items:
      - "{{ postgresql_user }}"
    tags: PostgresqlUser
