#..
# plyabook.yml - Esse playbook é responsável pela 'orquestração' das roles citadas
# no campo 'roles'. O intuito desse arquivo é instalar e configurar a estrutura mínima
# para o início do meu servidor compartilhado.
#
# O Script guarda:
# Variáveis   |    Conteúdo
#
# "site"          os domínios que precisam ser configurados presentes no nginx/sites-enabled
# ""    os subdomínios referentes ao domínio.
# ""     a versão do php do subdomínio.
#
# Busca nos arquivos                                  Conteúdo                            Salva na variável
# /etc/nginx/sites-enabled                            Domínio                             dominio
# /etc/nginx/sites-enabled/$dominio/$subdominio       Usuário/Versão do php/Plataforma    user/versaophp/magento
# /home[no caso do domínio ser em python e não php]   Usuário                             user
#
# Outras variáveis: redirect, redirect2 no caso de não encontrar a versão do php nem python, o redirect
# guarda para qual site o domínio em questão está sendo redirecionado e no caso de não ter o redirecionamento.
#
#
#
# Por Gabriel Fontes.
#

## Configurações de conexão --- Arquivo: hosts
- hosts: fontes
  gather_facts: no
  remote_user: root

### Variáveis
  vars:
    sites:
      - {dominio: 'fontes.aptans.com', version: 'php7.2-fpm', usuario: 'root'}

    mariadb_databases:
      - {name: 'zabbix', state: 'absent'}

    mariadb_users:
      - {name: 'zabbix', password: 'batatinha123', priv: 'zabbix.*:ALL', state: 'present' }

#    postgresql_databases:
#      - {name: 'wordpress'}

#    postgresql_user:
#      - {name: 'wordpress', password: 'batatinha123', priv: 'wordpress.*:ALL', base: 'wordpress'}
  
  roles:
    - php
    - mariadb
#    - postgresql
    - wordpress
    - nginx
#    - zabbix
#    - mysql
#    - myrepo
#    - borg
